#%RAML 0.8
---
title: P&O
version: v3

documentation:
  - title: Introductie
    content: !include docs/intro.md

schemas:
  - link:                               !include schemas/link.schema
  - gebruiker-basis:                    !include schemas/gebruiker-basis.schema
  - organisatie:                        !include schemas/organisatie.schema
  - toelating:                          !include schemas/toelating.schema
  - toepassing:                         !include schemas/toepassing.schema
  - toepassingen:                       !include schemas/toepassingen.schema
  - toepassing-basis:                   !include schemas/toepassing-basis.schema
  - toepassing-wijzig:                  !include schemas/toepassing-wijzig.schema
  - rol:                                !include schemas/rol.schema
  - taak-links:                         !include schemas/taak-links.schema
  - field-validation-error:             !include schemas/field-validation-error.schema

traits:
  - acceptjson:                         !include traits/acceptjson.yaml
  - paged:                              !include traits/paged.yaml
  - error401:                           !include traits/error401.yaml
  - error404:                           !include traits/error404.yaml
  - error412:                           !include traits/error412.yaml


/rest/toepassing:
  !include toepassing.raml

/rest/organigram:
  !include organigram.raml

