#%RAML 1.0
---
title: test01
version: 1.0
mediaType: application/json

types:
  Book:
    type: object
    properties:
      isbn:
        type: string
        required: true
      title:
        type: string
        required: true
      genre:
        type: string
      author:
        type: Author
        required: true
  Author:
    type: object
    properties:
      firstName:
        type: string
        required: true
      lastName:
        type: string
        required: true
  ComicBook:
    type: Book
    properties:
      hero:
        type: string
  Phone:
    type: object
    properties:
      manufacturer:
        type: string
      numberOfSIMCards:
        type: number
  Notebook:
    type: object
    properties:
      manufacturer:
        type: string
      numberOfUSBPorts:
        type: number
#  Person:
#    type: object
#    properties:
#      devices: ( Phone | Notebook )[]
#      reports: Person[]
#  PhoneOrNotebook: ( Phone | Notebook )
  HasHome:
    type: object
    properties:
      homeAddress: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string
  HomeAnimal:
    type: [ HasHome , Dog ]
    properties:
      indoor: boolean


/rest/books:
  get:
    description: Get all books
    responses:
      200:
        body:
          application/json:
            type: Book[]
