#%RAML 1.0
---
title: test01
version: v1

types:
  - user:           !include model/user.json
  - user-ext-req:   !include model/user-ext-req.json

/user:
  get:
    responses:
      200:
        body:
          application/json:
            type: user

/user-ext:
  get:
    responses:
      200:
        body:
          application/json:
            type: user-ext-req
