#%RAML 1.0
---
title: test01
version: v1

types:
  - link:         !include model/link.json
  - user:         !include model/user.json


#/rest/user:
#  !include user.raml
#
#/rest/animals:
#  !include animals.raml
