#%RAML 0.8
---
title: test01
version: v1

types:
  - link:         !include schemas/link.json
  - user:         !include schemas/user.json
  - animal:       !include schemas/animal.json
  - method:       !include schemas/method.json
  - paged-list:   !include schemas/paged-list.json
  - bbox:         !include schemas/geojson/bbox.json
  - crs:          !include schemas/geojson/crs.json
  - geometry:     !include schemas/geojson/geometry.json

traits:
  - error401:     !include schemas/common/traits/error401.yaml

/rest/user:
  !include user.raml

/rest/animals:
  !include animals.raml
